version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
      - mongo-db

  postgres-db:
    image: bitnami/postgresql:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - /init.sql

  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
