name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: matheuswenes
        password: trolados456

    - name: Build and push PostgreSQL image
      run: |
        docker-compose -f ./docker-compose.yml build postgres
        docker tag $(docker-compose -f ./docker-compose.yml images -q postgres) matheuswenes/postgresql:latest
        docker push matheuswenes/postgresql:latest

    - name: Build and push MongoDB image
      run: |
        docker-compose -f ./docker-compose.yml build mongo
        docker tag $(docker-compose -f ./docker-compose.yml images -q mongo) matheuswenes/mongo:latest
        docker push matheuswenes/mongo:latest
