name: Build and Push Docker Images

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: matheuswenes  
        password: trolados456

    - name: Build and push PostgreSQL image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./path/to/your/postgres/Dockerfile
        push: true
        tags: matheuswenes/postgresql:latest

    - name: Build and push MongoDB image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./path/to/your/mongo/Dockerfile
        push: true
        tags: matheuswenes/mongo:latest
