name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: matheuswenes
        password: moderador456

    - name: Build and push app image
      run: |
        docker build -t matheuswenes/app:latest .
        docker push matheuswenes/app:latest

    - name: Pull PostgreSQL image
      run: docker pull bitnami/postgresql:latest

    - name: Tag and push PostgreSQL image
      run: |
        docker tag bitnami/postgresql:latest matheuswenes/postgresql:latest
        docker push matheuswenes/postgresql:latest

    - name: Pull MongoDB image
      run: docker pull mongo:latest

    - name: Tag and push MongoDB image
      run: |
        docker tag mongo:latest matheuswenes/mongo:latest
        docker push matheuswenes/mongo:latest
