name: Barber-Integration

on:
  pull_request:
    branches:
      ['main']

jobs:
  Barber-Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using-Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 20.
        - name: run install, build and test
          run:
            npm i
            npm run build
            npm run test
